sudo: required
dist: trusty
language: node_js
node_js:
  - '16'
cache:
  yarn: true
  directories:
    - node_modules
    - '$HOME/.npm'
env:
  global:
    - secure: ZQqOBJy64PMbvk05OEv2tQ0LPT0lgFcYuGaH8WYmQsQn7leJlbsbEcKkVVWhfKPyWwitdxfMus60Fe6sr9XWAn3ZS8aOIWIdhQDQE51lpM79WOWXARmUkeRuRKRfLYjAQPehEX4c+HP0X240uiqsObPEsYxpo4aPWWOBibS/Q+S+efH9sh5ltTKk/ZDmvUzTTOCrArecMr9B7JvGidm8UFUHUiEycoBGAcnIJvnG0uZEl8q/Dq0ZoGSYFuZW6u9DPAjDc9Pw7RnDSYTaV438dmPT0I0Cdl6sjVZJgyRtCZ/Anee+NjNkGmqU9Tro7dtprqanaU4qLeARngTXGwzhyYy/xL3FylTxAk2bHdFAnqpfTIeDHz5UX/evrf78MgbVpN9LUy4+v2u8/sXt+XwATCDei/yWWoimDueRYcgVo8Ohs92h2zMAbwJlsunKmCa3Dt7bVxBi9ssUSDYR2tfgHNagFgJwvNLLdhx9yQ9pa1YSXUjp9aVK3iAGqwS5pUbZo1vZVR9iDVHeezB5/bwwigjIpJOC7yRmaMtRYSKcW+mc441XAI8R80PSduwun9Xmm9zH6deatbScfQqcMbE4gUj6uLQfmkhnJiuPvdSGHRemJakFj0/4zBaTspXjbJ5aEGACMKrq53/n/ZkSF412kTnOXpe6Rt5hNkyaqCLhmjE=
    - secure: yiNxscYptRvwwsNdjFFT3h0YfYST7Z3vOM5omWJ0U1omIAL00sm3zgLDKRlAoZL6CmgL5Ub1124g9UYBpWDAGCXFP6Hdz9i9zgNZVvE8wM/lExXcp3RQglyn4eYGtraOUGP0CiiPtT0Sh3/eT+mWVkf9sA5WLs8v2/ywzEKLjDoQ5yqE64g9hFS4K2B9UjlDpbsLvzFu2povlbvBihmV+g1NJW70PxzO4mCtGwNLGV2O/y/dwVQN+qUPfyEXb+WN0fVyRATM33YBCPFpX5ei6EFdtkMQDrk7186ekaExYrT9kJnKQ07aYpHM7568kJKfkopXo3wzbl7dvkTCjZs4HD0foDAnOErzdgo43/P6bKKLdjenf6jkduyIMqpI+tCo/UVk95RpIltDg2BH7MVQF5liN4hHJpQbhN6Q3DuTlaokDzh7sf/tIWuPbto8mteRGsOqxSpi51B3wXe/slS5PSl4XTPUedM8KjsKDjWV5eY92LWO7ThnhSbSI5hHsNIz7LgS4iARymf1/ypCDoO4lDiW5Sfc2Sd3jv2Dox6Yi39hiL+3Tpj+TvYb65VW99cKN/o4RJlRka3aq4uRlJwH+mkM/NuQkhSOg7DyfPM8iSqd1hnYqnfxSx8JVfDRYPoc8jR+8XmgJDSC0RLHJjn/a3MVmNkxAwNIhzu02s6KD+Y=
before_install:
  - openssl aes-256-cbc -K $encrypted_4a8eabd2975a_key -iv $encrypted_4a8eabd2975a_iv
    -in travis/secrets.tar.enc -out travis/secrets.tar -d
  - tar xvf travis/secrets.tar
  - mv id_rsa /home/travis/.ssh/id_rsa
  - chmod 700 /home/travis/.ssh/id_rsa
  - npm install pm2 -g
  - cd api
  - chmod +x ../travis/${TRAVIS_BRANCH}.sh
  - '../travis/${TRAVIS_BRANCH}.sh'
before_script:
  - cd ../
  - mkdir storage
  - chmod +x scripts/deploy.sh
  - git config core.fileMode false
script:
  - echo "Run Script"
deploy:
  - provider: script
    script: scripts/deploy.sh
    on:
      branch: master
  - provider: script
    script: scripts/deploy.sh
    on:
      branch: staging
