version: '2'
services:
  pinyin_db:
    hostname: db
    container_name: pinyin_db
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "pinyin"
      MYSQL_USER: "docker"
      MYSQL_PASSWORD: "docker"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./api/storage/mysql:/var/lib/mysql

  pinyin_redis:
    hostname: redis
    container_name: pinyin_redis
    image: redis:4
    volumes:
      - ./api/storage/redis:/data

  pinyin_api:
    hostname: api
    container_name: pinyin_api
    build: ./docker/api
    user: "node"
    working_dir: /home/node/pinyin/api
    environment:
      - NODE_ENV=development
    ports:
      - "9090:9090"
    links:
      - pinyin_db
      - pinyin_redis
    volumes:
      - ./:/home/node/pinyin
    command: "yarn dev"

  # pinyin_elasticsearch:
  #   hostname: elasticsearch
  #   container_name: pinyin_elasticsearch
  #   image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
  #   environment:
  #     - cluster.name=docker-cluster
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   ports:
  #     - "9200:9200"
  #   volumes:
  #     - ./docker/data/elasticsearch:/usr/share/elasticsearch/data

  # pinyin_kibana:
  #   hostname: kibana
  #   container_name: pinyin_kibana
  #   image: docker.elastic.co/kibana/kibana:6.1.1
  #   environment:
  #     -  ELASTICSEARCH_URL=http://pinyin_elasticsearch:9200
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   links:
  #     - pinyin_elasticsearch
  #   ports:
  #     - "5601:5601"

