# Change on the UI:
# Ubuntu Build Image to 16.04
# PYTHON_VERSION=3.7
# AWS_LAMBDA_JS_RUNTIME=nodejs16.x
[dev]
port = 8885
autoLaunch = false

[build]
base = "services/jieba"
command = "ls -la && mkdir dict && cp node_modules/separate-chinese-words/dict/* dict/"

[functions]
