module.exports = {
  google_client_id: '',
  google_client_secret: '',
  baidu_client_id: '',
  baidu_client_secret: '',
  jwt_key: '',
  front_url: '',
  storage_path: '',
  redis_host: '',
  redis_port: '',
  database_port: '',
  database_name: '',
  database_host: '',
  database_user: '',
  database_pass: '',
  sentry_dsn: '',
  files_adapter: '', // local or s3
  aws_region: '',
  aws_access_key_id: '',
  aws_secret_access_key: '',
  aws_s3_bucket: '',
  elasticsearch_host: '',
  elasticsearch_port: '',
  '2pinyin_token': '',
};
