name: Deploy
'on':
  push:
    branches:
      - master
jobs:
  Build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-22.04
        node-version:
          - 16.x
    steps:
      - name: 'Set up Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v1
        with:
          node-version: '${{ matrix.node-version }}'
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |-
            node_modules
            $HOME/.npm
          key: '${{ runner.os }}-${{ hashFiles(''TODO'') }}'
      - uses: actions/checkout@v2
      - run: pwd
      # - run: >-
      #     openssl aes-256-cbc -K $encrypted_4a8eabd2975a_key -iv
      #     $encrypted_4a8eabd2975a_iv -in travis/secrets.tar.enc -out
      #     travis/secrets.tar -d
      # - run: tar xvf travis/secrets.tar
      # - run: mv id_rsa /home/travis/.ssh/id_rsa
      # - run: chmod 700 /home/travis/.ssh/id_rsa
      - run: npm install pm2 -g
      - run: bash travis/master.sh
      - run: mkdir storage
      - run: bash scripts/deploy.sh
      - run: git config core.fileMode false
      - run: echo "Run Script"
